### PANDAS ###

In [16]:
import pandas as pd

In [17]:
pd.Series([45,5455,55,12,225])

0      45
1    5455
2      55
3      12
4     225
dtype: int64

In [18]:
x=pd.Series([45,5455,55,12,225])

In [19]:
type(x)

pandas.core.series.Series

In [20]:
x.axes

[RangeIndex(start=0, stop=5, step=1)]

In [21]:
x.dtype

dtype('int64')

In [22]:
x.size

5

In [23]:
x.ndim

1

In [24]:
x.values

array([  45, 5455,   55,   12,  225], dtype=int64)

In [25]:
x.head(2)

0      45
1    5455
dtype: int64

In [26]:
x.tail(2)

3     12
4    225
dtype: int64

In [27]:
x=pd.Series([45,5455,55,12,225], index=[2,5,7,8,5])
x

2      45
5    5455
7      55
8      12
5     225
dtype: int64

In [28]:
x[1:3]

5    5455
7      55
dtype: int64

In [29]:
x[2]

45

In [30]:
x=pd.Series([45,5455,55,12,225], index=['x','y','z','t','m'])
x

x      45
y    5455
z      55
t      12
m     225
dtype: int64

In [31]:
x['y':'t']

y    5455
z      55
t      12
dtype: int64

In [32]:
x['z']

55

In [33]:
dicti={'std':15,'mean':45,'mod':5}

In [34]:
a=pd.Series(dicti)
a

std     15
mean    45
mod      5
dtype: int64

In [35]:
a[0]

15

In [36]:
a['std':'mean']

std     15
mean    45
dtype: int64

In [37]:
y=pd.Series([5,5,12,35])
y

0     5
1     5
2    12
3    35
dtype: int64

In [38]:
pd.concat([x,y])

x      45
y    5455
z      55
t      12
m     225
0       5
1       5
2      12
3      35
dtype: int64

In [39]:
pd.concat([x,a])

x         45
y       5455
z         55
t         12
m        225
std       15
mean      45
mod        5
dtype: int64

### Element operations ###

In [40]:
import numpy as np
import pandas as pd

In [41]:
t=np.array([4,5,6,8,9,12])

In [42]:
u=pd.Series(t)
u

0     4
1     5
2     6
3     8
4     9
5    12
dtype: int32

In [43]:
t[2]

6

In [44]:
t[1:4]

array([5, 6, 8])

In [45]:
u.index

RangeIndex(start=0, stop=6, step=1)

In [46]:
u.keys

<bound method Series.keys of 0     4
1     5
2     6
3     8
4     9
5    12
dtype: int32>

In [47]:
list(u.items())

[(0, 4), (1, 5), (2, 6), (3, 8), (4, 9), (5, 12)]

In [48]:
u.values

array([ 4,  5,  6,  8,  9, 12])

In [49]:
6 in u

False

In [61]:
1 in u

True

#### Fancy Element ####

In [63]:
u[[1, 2]]                       # give the name of series to find the value.

1    5
2    6
dtype: int32

In [64]:
u[1]

5

In [65]:
u[1]=555

In [66]:
u

0      4
1    555
2      6
3      8
4      9
5     12
dtype: int32

### Create a Dataframe ###

In [68]:
p=[1,2,3,4,5,6,7]

In [69]:
import pandas as pd

In [74]:
pd.DataFrame(p, columns=['data'])

data
0     1
1     2
2     3
3     4
4     5
5     6
6     7

In [77]:
import numpy as np

In [326]:
s=np.arange(1,10).reshape(3,3)
s

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
pd.DataFrame(s, columns=['data1','data2','data3'])             #create a dataframe from any numpy array.

data1  data2  data3
0      1      2      3
1      4      5      6
2      7      8      9

In [86]:
df=pd.DataFrame(s, columns=['value1','value2','value3'])
df

value1  value2  value3
0       1       2       3
1       4       5       6
2       7       8       9

In [87]:
df.columns

Index(['value1', 'value2', 'value3'], dtype='object')

In [89]:
df.columns=('x','y','z')
df

x  y  z
0  1  2  3
1  4  5  6
2  7  8  9

In [90]:
type(df)

pandas.core.frame.DataFrame

In [91]:
df.axes

[RangeIndex(start=0, stop=3, step=1), Index(['x', 'y', 'z'], dtype='object')]

In [92]:
df.shape

(3, 3)

In [93]:
df.ndim

2

In [94]:
df.size

9

In [95]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [96]:
type(df.values)

numpy.ndarray

In [97]:
df.head()

x  y  z
0  1  2  3
1  4  5  6
2  7  8  9

In [100]:
df.head(1)

x  y  z
0  1  2  3

In [98]:
df.tail()

x  y  z
0  1  2  3
1  4  5  6
2  7  8  9

In [101]:
df.tail(1)

x  y  z
2  7  8  9

#### Element Operations in DataFrame ####

In [224]:
import numpy as np

In [225]:
n1=np.random.randint(10, size=5)
n2=n1=np.random.randint(10, size=5)
n3=n1=np.random.randint(10, size=5)

In [226]:
dicti={'m1':n1, 'm2':n2, 'm3':n3}

In [227]:
dicti                                     # Values are numpy array.

{'m1': array([6, 2, 4, 8, 0]),
 'm2': array([9, 2, 1, 8, 8]),
 'm3': array([6, 2, 4, 8, 0])}

In [292]:
df=pd.DataFrame(dicti)
df                                        # The dataframe is from the dictionary. 

m1  m2  m3
0   6   9   6
1   2   2   2
2   4   1   4
3   8   8   8
4   0   8   0

In [293]:
df[0:1]

m1  m2  m3
0   6   9   6

In [294]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [295]:
df.index=['a','b','c','d','e']
df

m1  m2  m3
a   6   9   6
b   2   2   2
c   4   1   4
d   8   8   8
e   0   8   0

In [296]:
df[:'a']

m1  m2  m3
a   6   9   6

In [297]:
df['a':'b']

m1  m2  m3
a   6   9   6
b   2   2   2

In [298]:
df['b':'d']

m1  m2  m3
b   2   2   2
c   4   1   4
d   8   8   8

In [299]:
g=['a']

In [302]:
df.loc['b', 'm2']            #We want to see one element-loc

2

In [303]:
df.loc['c', 'm2']

1

In [ ]:
df.(, axis=0)

#### Drop ####

In [117]:
df.drop('a', axis=0)

m1  m2  m3
b   4   5   4
c   4   8   4
d   1   3   1
e   2   8   2

In [119]:
df.drop('m1', axis=1)

m2  m3
a   7   3
b   5   4
c   8   4
d   3   1
e   8   2

In [126]:
df

m1  m2  m3
b   4   5   4
c   4   8   4
d   1   3   1
e   2   8   2

In [130]:
df.drop('b', axis=0, inplace=True)
df

m1  m2  m3
c   4   8   4
d   1   3   1
e   2   8   2

In [131]:
df.drop('m3', axis=1, inplace=True)
df

m1  m2
c   4   8
d   1   3
e   2   8

#### Fancy Operation ####

#### type : 1 ####

In [132]:
y=['c','e']

In [133]:
df.drop(y, axis=0)

m1  m2
d   1   3

In [147]:
df

m1  m2
c   4   8
d   1   3
e   2   8

#### type : 2 ####

In [148]:
df.drop(['c','e'], axis=0)

m1  m2
d   1   3

In [149]:
df

m1  m2
c   4   8
d   1   3
e   2   8

In [150]:
'm1' in df

True

In [153]:
l=['var1','var2','m1','d']

In [154]:
for i in l:
    print(i in df)

False
False
True
False


In [155]:
df

m1  m2
c   4   8
d   1   3
e   2   8

In [157]:
df['var4']=df['m1']*df['m2']

In [158]:
df

m1  m2  var4
c   4   8    32
d   1   3     3
e   2   8    16

In [159]:
df.drop('var4', axis=1)

m1  m2
c   4   8
d   1   3
e   2   8

In [160]:
df

m1  m2  var4
c   4   8    32
d   1   3     3
e   2   8    16

df.drop('var4', axis=1, inplace=True)

In [163]:
df.drop('m1', axis=1, inplace=True)

In [164]:
df

m2
c   8
d   3
e   8

In [165]:
df.drop('c', axis=0, inplace=True)

In [166]:
df

m2
d   3
e   8

gözlem and değişken selection

In [268]:
import numpy as np

In [269]:
e=np.random.randint(1,30, size=(10,3))
e

array([[10,  4, 19],
       [19, 24, 21],
       [29,  6, 10],
       [13,  5,  2],
       [13,  5, 12],
       [19,  7, 27],
       [ 9, 21,  9],
       [10, 17,  7],
       [24, 14, 26],
       [21, 29, 17]])

In [284]:
import pandas as pd

In [285]:
df=pd.DataFrame(e, columns=['mean1','mean2','mean3'])
df

mean1  mean2  mean3
0     10      4     19
1     19     24     21
2     29      6     10
3     13      5      2
4     13      5     12
5     19      7     27
6      9     21      9
7     10     17      7
8     24     14     26
9     21     29     17

In [286]:
df[0:3]

mean1  mean2  mean3
0     10      4     19
1     19     24     21
2     29      6     10

In [287]:
df.loc[0:3]

mean1  mean2  mean3
0     10      4     19
1     19     24     21
2     29      6     10
3     13      5      2

In [289]:
df.loc[4:6]                              #-6 include

mean1  mean2  mean3
4     13      5     12
5     19      7     27
6      9     21      9

In [283]:
df.loc[:6]

mean1  mean2  mean3
0     10      4     19
1     19     24     21
2     29      6     10
3     13      5      2
4     13      5     12
5     19      7     27
6      9     21      9

In [279]:
df.loc[4,'mean1']                        

13

In [182]:
df.iloc[4:6]                           # up to 6

mean1  mean2  mean3
4     11      5     12
5      6     15     27

In [186]:
df.iloc[:4,:1]   

mean1
0     10
1     10
2      3
3      2

In [187]:
df.loc[:4,'mean2']

0     7
1    21
2    20
3    17
4     5
Name: mean2, dtype: int32

In [191]:
df.iloc[:4]['mean2']

0     7
1    21
2    20
3    17
Name: mean2, dtype: int32

### Conditional ###

In [50]:
import numpy as np

In [51]:
p=np.random.randint(45, size=[9,5])
p

array([[36, 20,  2, 18,  9],
       [20, 27, 18, 11, 27],
       [11, 36, 20, 36,  0],
       [20, 26, 28, 10, 31],
       [38, 19, 32, 18, 41],
       [40, 14, 13, 34, 22],
       [20,  6, 15,  0, 41],
       [ 0, 20, 10,  8,  5],
       [41,  5, 21,  0, 13]])

In [52]:
import pandas as np

In [53]:
q=pd.DataFrame(p)
q

0   1   2   3   4
0  36  20   2  18   9
1  20  27  18  11  27
2  11  36  20  36   0
3  20  26  28  10  31
4  38  19  32  18  41
5  40  14  13  34  22
6  20   6  15   0  41
7   0  20  10   8   5
8  41   5  21   0  13

In [54]:
q=pd.DataFrame(p, columns=(['std1','std2','std3','std4','std5']))
q

std1  std2  std3  std4  std5
0    36    20     2    18     9
1    20    27    18    11    27
2    11    36    20    36     0
3    20    26    28    10    31
4    38    19    32    18    41
5    40    14    13    34    22
6    20     6    15     0    41
7     0    20    10     8     5
8    41     5    21     0    13

In [55]:
q['label']=q['std1']*q['std2']

In [56]:
q

std1  std2  std3  std4  std5  label
0    36    20     2    18     9    720
1    20    27    18    11    27    540
2    11    36    20    36     0    396
3    20    26    28    10    31    520
4    38    19    32    18    41    722
5    40    14    13    34    22    560
6    20     6    15     0    41    120
7     0    20    10     8     5      0
8    41     5    21     0    13    205

In [57]:
q['label']

0    720
1    540
2    396
3    520
4    722
5    560
6    120
7      0
8    205
Name: label, dtype: int32

In [58]:
q[:2][['std1','label']]        #If we see one more variable,we must use 'fancy'for instance:'std1' and 'label' is made a list.
                               #But when we see one or one more feature,we use ['any feature']or ['any feature':'any feature']

std1  label
0    36    720
1    20    540

In [314]:
q

std1  std2  std3  std4  std5  label
0    19    19    15    44    31    361
1    25    13    41     8    39    325
2     4    44    24     3    11    176
3    30    24    43     5     0    720
4    13    41    19    27     8    533
5    28    42    34    35     7   1176
6    35     9    36    40    26    315
7     6    39    30     9    37    234
8    11    16    26     1    44    176

In [315]:
q[q.std1>12]                  #Select bigger than 12 number in 'std1'.

std1  std2  std3  std4  std5  label
0    19    19    15    44    31    361
1    25    13    41     8    39    325
3    30    24    43     5     0    720
4    13    41    19    27     8    533
5    28    42    34    35     7   1176
6    35     9    36    40    26    315

In [316]:
q[q.std1>12]['std2']          #And than select this conclusion in 'std2'

0    19
1    13
3    24
4    41
5    42
6     9
Name: std2, dtype: int32

In [317]:
q[(q.std1>12) & (q.std4>15)]

std1  std2  std3  std4  std5  label
0    19    19    15    44    31    361
4    13    41    19    27     8    533
5    28    42    34    35     7   1176
6    35     9    36    40    26    315

example-1

In [318]:
q.loc[(q.std1>12), ['std1', 'std2']]         

std1  std2
0    19    19
1    25    13
3    30    24
4    13    41
5    28    42
6    35     9

example-2

In [59]:
q[(q.std1>12)][['std1','std2']]       #This is the same with 'example1'.

std1  std2
0    36    20
1    20    27
3    20    26
4    38    19
5    40    14
6    20     6
8    41     5

### Join ###

In [60]:
import numpy as np

In [63]:
w=np.array([452,5525,581848,1,233])                 #We use 'array' for one dimension.
w

array([   452,   5525, 581848,      1,    233])

In [69]:
q=np.arange(0,30).reshape(5,6)                     #We use 'arange' for more one than dimension.
q

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [70]:
pd.DataFrame(q)

0   1   2   3   4   5
0   0   1   2   3   4   5
1   6   7   8   9  10  11
2  12  13  14  15  16  17
3  18  19  20  21  22  23
4  24  25  26  27  28  29

In [72]:
h=pd.DataFrame(q, columns=['colour_degree1','colour_degree2','colour_degree3','colour_degree4','colour_degree5','colour_degree6'])
h

colour_degree1  colour_degree2  colour_degree3  colour_degree4  \
0               0               1               2               3   
1               6               7               8               9   
2              12              13              14              15   
3              18              19              20              21   
4              24              25              26              27   

   colour_degree5  colour_degree6  
0               4               5  
1              10              11  
2              16              17  
3              22              23  
4              28              29

In [98]:
h2=h+5
h2

colour_degree1  colour_degree2  colour_degree3  colour_degree4  \
0               5               6               7               8   
1              11              12              13              14   
2              17              18              19              20   
3              23              24              25              26   
4              29              30              31              32   

   colour_degree5  colour_degree6  
0               9              10  
1              15              16  
2              21              22  
3              27              28  
4              33              34

In [99]:
pd.concat([h,h2])

colour_degree1  colour_degree2  colour_degree3  colour_degree4  \
0               0               1               2               3   
1               6               7               8               9   
2              12              13              14              15   
3              18              19              20              21   
4              24              25              26              27   
0               5               6               7               8   
1              11              12              13              14   
2              17              18              19              20   
3              23              24              25              26   
4              29              30              31              32   

   colour_degree5  colour_degree6  
0               4               5  
1              10              11  
2              16              17  
3              22              23  
4              28              29  
0               9              10  
1              15              16  
2              21              22  
3              27              28  
4              33              34

In [100]:
pd.concat([h,h2], ignore_index=True)

colour_degree1  colour_degree2  colour_degree3  colour_degree4  \
0               0               1               2               3   
1               6               7               8               9   
2              12              13              14              15   
3              18              19              20              21   
4              24              25              26              27   
5               5               6               7               8   
6              11              12              13              14   
7              17              18              19              20   
8              23              24              25              26   
9              29              30              31              32   

   colour_degree5  colour_degree6  
0               4               5  
1              10              11  
2              16              17  
3              22              23  
4              28              29  
5               9              10  
6              15              16  
7              21              22  
8              27              28  
9              33              34

In [105]:
h2

colour_degree1  colour_degree2  colour_degree3  colour_degree4  \
0               5               6               7               8   
1              11              12              13              14   
2              17              18              19              20   
3              23              24              25              26   
4              29              30              31              32   

   colour_degree5  colour_degree6  
0               9              10  
1              15              16  
2              21              22  
3              27              28  
4              33              34

In [108]:
h2.columns=['colour_degree1','colour_degree2','colour_degree3','colour_degree4','colour_high1','colour_high2']

In [109]:
h2

colour_degree1  colour_degree2  colour_degree3  colour_degree4  \
0               5               6               7               8   
1              11              12              13              14   
2              17              18              19              20   
3              23              24              25              26   
4              29              30              31              32   

   colour_high1  colour_high2  
0             9            10  
1            15            16  
2            21            22  
3            27            28  
4            33            34

In [111]:
pd.concat([h,h2])

colour_degree1  colour_degree2  colour_degree3  colour_degree4  \
0               0               1               2               3   
1               6               7               8               9   
2              12              13              14              15   
3              18              19              20              21   
4              24              25              26              27   
0               5               6               7               8   
1              11              12              13              14   
2              17              18              19              20   
3              23              24              25              26   
4              29              30              31              32   

   colour_degree5  colour_degree6  colour_high1  colour_high2  
0             4.0             5.0           NaN           NaN  
1            10.0            11.0           NaN           NaN  
2            16.0            17.0           NaN           NaN  
3            22.0            23.0           NaN           NaN  
4            28.0            29.0           NaN           NaN  
0             NaN             NaN           9.0          10.0  
1             NaN             NaN          15.0          16.0  
2             NaN             NaN          21.0          22.0  
3             NaN             NaN          27.0          28.0  
4             NaN             NaN          33.0          34.0

In [123]:
pd.concat([h,h2], join='inner')

colour_degree1  colour_degree2  colour_degree3  colour_degree4
0               0               1               2               3
1               6               7               8               9
2              12              13              14              15
3              18              19              20              21
4              24              25              26              27
0               5               6               7               8
1              11              12              13              14
2              17              18              19              20
3              23              24              25              26
4              29              30              31              32

In [137]:
pd.concat([h,h2] join_axes =[h2.columns])

SyntaxError: invalid syntax (<ipython-input-137-2d61448cd971>, line 1)

### Advanced Join ###

In [126]:
import pandas as pd

In [129]:
df1=pd.DataFrame({'staff_name':['john','george','maria','ali'],
                 'staff_age':[5,5,64,18]})
df1

staff_name  staff_age
0       john          5
1     george          5
2      maria         64
3        ali         18

In [132]:
df2=pd.DataFrame({'staff_name':['john','george','maria','ali'],'start_work':[2000,2001,2002,2003]})
df2

staff_name  start_work
0       john        2000
1     george        2001
2      maria        2002
3        ali        2003

In [146]:
df3=pd.merge(df1,df2)  
df3                                              #'merge' is a  one-to-one merge

staff_name  staff_age  start_work
0       john          5        2000
1     george          5        2001
2      maria         64        2002
3        ali         18        2003

In [143]:
pd.merge(df1,df2, on ='staff_name')

staff_name  staff_age  start_work
0       john          5        2000
1     george          5        2001
2      maria         64        2002
3        ali         18        2003

In [153]:
df4=pd.DataFrame({'staff_age':[5,5,64], 'staff_periyod':['morning','noon','evening']})
df4                                                                                      #many-to-one merge

staff_age staff_periyod
0          5       morning
1          5          noon
2         64       evening

In [155]:
pd.merge(df3,df4)

staff_name  staff_age  start_work staff_periyod
0       john          5        2000       morning
1       john          5        2000          noon
2     george          5        2001       morning
3     george          5        2001          noon
4      maria         64        2002       evening

In [ ]:
df5=({'staff_name':['john','george','maria','ali',''],})                                                                                               #many to many

### Agreegation and Grouping ###

Agreegation Functions
* count() - 
* first()-
* last()-
* mean()-
* median()-
* min()-
* max()-
* std()-
* var()-
* sum()-

In [16]:
import seaborn as sns

In [17]:
df=sns.load_dataset('planets')
df

method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1035 rows x 6 columns]

In [18]:
df.head(15)

method  number  orbital_period   mass  distance  year
0   Radial Velocity       1         269.300   7.10     77.40  2006
1   Radial Velocity       1         874.774   2.21     56.95  2008
2   Radial Velocity       1         763.000   2.60     19.84  2011
3   Radial Velocity       1         326.030  19.40    110.62  2007
4   Radial Velocity       1         516.220  10.50    119.47  2009
5   Radial Velocity       1         185.840   4.80     76.39  2008
6   Radial Velocity       1        1773.400   4.64     18.15  2002
7   Radial Velocity       1         798.500    NaN     21.41  1996
8   Radial Velocity       1         993.300  10.30     73.10  2008
9   Radial Velocity       2         452.800   1.99     74.79  2010
10  Radial Velocity       2         883.000   0.86     74.79  2010
11  Radial Velocity       1         335.100   9.88     39.43  2009
12  Radial Velocity       1         479.100   3.88     97.28  2008
13  Radial Velocity       3        1078.000   2.53     14.08  1996
14  Radial Velocity       3        2391.000   0.54     14.08  2001

In [19]:
df.shape

(1035, 6)

In [20]:
df.count()

method            1035
number            1035
orbital_period     992
mass               513
distance           808
year              1035
dtype: int64

In [21]:
df['number'].count()

1035

In [22]:
df.first()

TypeError: first() missing 1 required positional argument: 'offset'

In [23]:
df.last()

TypeError: last() missing 1 required positional argument: 'offset'

In [24]:
df.mean()

number               1.785507
orbital_period    2002.917596
mass                 2.638161
distance           264.069282
year              2009.070531
dtype: float64

In [25]:
df['mass'].mean()

2.6381605847953216

In [26]:
df.median()

number               1.0000
orbital_period      39.9795
mass                 1.2600
distance            55.2500
year              2010.0000
dtype: float64

In [27]:
df['distance'].median()

55.25

In [28]:
df.std()

number                1.240976
orbital_period    26014.728304
mass                  3.818617
distance            733.116493
year                  3.972567
dtype: float64

In [29]:
df['orbital_period'].std()

26014.728304062508

In [30]:
df.var()

number            1.540022e+00
orbital_period    6.767661e+08
mass              1.458183e+01
distance          5.374598e+05
year              1.578129e+01
dtype: float64

In [31]:
df['year'].var()

15.78128743494146

In [32]:
df.sum()

method            Radial VelocityRadial VelocityRadial VelocityR...
number                                                         1848
orbital_period                                          1.98689e+06
mass                                                        1353.38
distance                                                     213368
year                                                        2079388
dtype: object

In [33]:
df['mass'].sum()

1353.37638

In [34]:
df.max()

method            Transit Timing Variations
number                                    7
orbital_period                       730000
mass                                     25
distance                               8500
year                                   2014
dtype: object

In [35]:
df['mass'].max()

25.0

In [36]:
df.min()

method            Astrometry
number                     1
orbital_period     0.0907063
mass                  0.0036
distance                1.35
year                    1989
dtype: object

In [37]:
df['distance'].min()

1.35

In [38]:
df.describe()

number  orbital_period        mass     distance         year
count  1035.000000      992.000000  513.000000   808.000000  1035.000000
mean      1.785507     2002.917596    2.638161   264.069282  2009.070531
std       1.240976    26014.728304    3.818617   733.116493     3.972567
min       1.000000        0.090706    0.003600     1.350000  1989.000000
25%       1.000000        5.442540    0.229000    32.560000  2007.000000
50%       1.000000       39.979500    1.260000    55.250000  2010.000000
75%       2.000000      526.005000    3.040000   178.500000  2012.000000
max       7.000000   730000.000000   25.000000  8500.000000  2014.000000

In [39]:
df.describe().T

count         mean           std          min         25%  \
number          1035.0     1.785507      1.240976     1.000000     1.00000   
orbital_period   992.0  2002.917596  26014.728304     0.090706     5.44254   
mass             513.0     2.638161      3.818617     0.003600     0.22900   
distance         808.0   264.069282    733.116493     1.350000    32.56000   
year            1035.0  2009.070531      3.972567  1989.000000  2007.00000   

                      50%       75%       max  
number             1.0000     2.000       7.0  
orbital_period    39.9795   526.005  730000.0  
mass               1.2600     3.040      25.0  
distance          55.2500   178.500    8500.0  
year            2010.0000  2012.000    2014.0

In [40]:
df.dropna().describe()                            #We see missing valuble with 'dropna'

number  orbital_period        mass    distance         year
count  498.00000      498.000000  498.000000  498.000000   498.000000
mean     1.73494      835.778671    2.509320   52.068213  2007.377510
std      1.17572     1469.128259    3.636274   46.596041     4.167284
min      1.00000        1.328300    0.003600    1.350000  1989.000000
25%      1.00000       38.272250    0.212500   24.497500  2005.000000
50%      1.00000      357.000000    1.245000   39.940000  2009.000000
75%      2.00000      999.600000    2.867500   59.332500  2011.000000
max      6.00000    17337.500000   25.000000  354.000000  2014.000000

#### Aggregate ####

#### We only see statistics values with 'aggregate' that we want. ####

In [41]:
df3=pd.DataFrame({'student_class':['A','B','C','A','B'],'student_degree':[25,45,23,85,98],'student_age':[12,13,11,10,14]})
df3

student_class  student_degree  student_age
0             A              25           12
1             B              45           13
2             C              23           11
3             A              85           10
4             B              98           14

In [42]:
df3.groupby('student_class')

In [43]:
df3.groupby('student_class').mean()

student_degree  student_age
student_class                             
A                        55.0         11.0
B                        71.5         13.5
C                        23.0         11.0

In [66]:
df3.groupby('student_class').aggregate([max, min])

student_degree     student_age    
                         max min         max min
student_class                                   
A                         85  25          12  10
B                         98  45          14  13
C                         23  23          11  11

In [67]:
df

method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1035 rows x 6 columns]

In [68]:
df.head(5)

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [78]:
df.groupby('method').aggregate([min, max])

number     orbital_period                 \
                                 min max            min            max   
method                                                                   
Astrometry                         1   1     246.360000    1016.000000   
Eclipse Timing Variations          1   2    1916.250000   10220.000000   
Imaging                            1   4    4639.150000  730000.000000   
Microlensing                       1   2    1825.000000    5100.000000   
Orbital Brightness Modulation      1   2       0.240104       1.544929   
Pulsar Timing                      1   3       0.090706   36525.000000   
Pulsation Timing Variations        1   1    1170.000000    1170.000000   
Radial Velocity                    1   6       0.736540   17337.500000   
Transit                            1   7       0.355000     331.600590   
Transit Timing Variations          2   3      22.339500     160.000000   

                                 mass        distance           year        
                                  min    max      min      max   min   max  
method                                                                      
Astrometry                        NaN    NaN    14.98    20.77  2010  2013  
Eclipse Timing Variations      4.2000   6.05   130.72   500.00  2008  2012  
Imaging                           NaN    NaN     7.69   165.00  2004  2013  
Microlensing                      NaN    NaN  1760.00  7720.00  2004  2013  
Orbital Brightness Modulation     NaN    NaN  1180.00  1180.00  2011  2013  
Pulsar Timing                     NaN    NaN  1200.00  1200.00  1992  2011  
Pulsation Timing Variations       NaN    NaN      NaN      NaN  2007  2007  
Radial Velocity                0.0036  25.00     1.35   354.00  1989  2014  
Transit                        1.4700   1.47    38.00  8500.00  2002  2014  
Transit Timing Variations         NaN    NaN   339.00  2119.00  2011  2014

In [79]:
df.groupby('method')['mass'].aggregate([min, max])

min    max
method                                      
Astrometry                        NaN    NaN
Eclipse Timing Variations      4.2000   6.05
Imaging                           NaN    NaN
Microlensing                      NaN    NaN
Orbital Brightness Modulation     NaN    NaN
Pulsar Timing                     NaN    NaN
Pulsation Timing Variations       NaN    NaN
Radial Velocity                0.0036  25.00
Transit                        1.4700   1.47
Transit Timing Variations         NaN    NaN

#### Grouping ####

#### We are able to use 'groupby',if data type is categoric. ####

In [45]:
df1=pd.DataFrame({'student_class':['A','B','A','B'],'lecture_degree':[45,52,17,99]})

In [46]:
df1

student_class  lecture_degree
0             A              45
1             B              52
2             A              17
3             B              99

In [47]:
df1.groupby('student_class')

In [48]:
df1.groupby('student_class').mean()

lecture_degree
student_class                
A                        31.0
B                        75.5

In [49]:
df1.groupby('student_class').sum()

lecture_degree
student_class                
A                          62
B                         151

In [50]:
df

method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1035 rows x 6 columns]

In [51]:
df.groupby('method').std()

number  orbital_period      mass  \
method                                                              
Astrometry                     0.000000      544.217663       NaN   
Eclipse Timing Variations      0.500000     2499.130945  1.308148   
Imaging                        0.933035   213978.177277       NaN   
Microlensing                   0.387553     1113.166333       NaN   
Orbital Brightness Modulation  0.577350        0.725493       NaN   
Pulsar Timing                  1.095445    16313.265573       NaN   
Pulsation Timing Variations         NaN             NaN       NaN   
Radial Velocity                1.157141     1454.926210  3.825883   
Transit                        1.399119       46.185893       NaN   
Transit Timing Variations      0.500000       71.599884       NaN   

                                  distance      year  
method                                                
Astrometry                        4.094148  2.121320  
Eclipse Timing Variations       213.203907  1.414214  
Imaging                          53.736817  2.781901  
Microlensing                   2076.611556  2.859697  
Orbital Brightness Modulation     0.000000  1.154701  
Pulsar Timing                          NaN  8.384510  
Pulsation Timing Variations            NaN       NaN  
Radial Velocity                  45.559381  4.249052  
Transit                         913.876990  2.077867  
Transit Timing Variations       915.819487  1.290994

In [52]:
df.groupby('method').std().head(3)

number  orbital_period      mass    distance  \
method                                                                      
Astrometry                 0.000000      544.217663       NaN    4.094148   
Eclipse Timing Variations  0.500000     2499.130945  1.308148  213.203907   
Imaging                    0.933035   213978.177277       NaN   53.736817   

                               year  
method                               
Astrometry                 2.121320  
Eclipse Timing Variations  1.414214  
Imaging                    2.781901

In [53]:
df.groupby('method')['mass']

In [54]:
df.groupby('method')['mass'].mean()

method
Astrometry                            NaN
Eclipse Timing Variations        5.125000
Imaging                               NaN
Microlensing                          NaN
Orbital Brightness Modulation         NaN
Pulsar Timing                         NaN
Pulsation Timing Variations           NaN
Radial Velocity                  2.630699
Transit                          1.470000
Transit Timing Variations             NaN
Name: mass, dtype: float64

In [55]:
df.groupby('method')['mass'].describe()

count      mean       std     min      25%  \
method                                                                      
Astrometry                       0.0       NaN       NaN     NaN      NaN   
Eclipse Timing Variations        2.0  5.125000  1.308148  4.2000  4.66250   
Imaging                          0.0       NaN       NaN     NaN      NaN   
Microlensing                     0.0       NaN       NaN     NaN      NaN   
Orbital Brightness Modulation    0.0       NaN       NaN     NaN      NaN   
Pulsar Timing                    0.0       NaN       NaN     NaN      NaN   
Pulsation Timing Variations      0.0       NaN       NaN     NaN      NaN   
Radial Velocity                510.0  2.630699  3.825883  0.0036  0.22525   
Transit                          1.0  1.470000       NaN  1.4700  1.47000   
Transit Timing Variations        0.0       NaN       NaN     NaN      NaN   

                                 50%     75%    max  
method                                               
Astrometry                       NaN     NaN    NaN  
Eclipse Timing Variations      5.125  5.5875   6.05  
Imaging                          NaN     NaN    NaN  
Microlensing                     NaN     NaN    NaN  
Orbital Brightness Modulation    NaN     NaN    NaN  
Pulsar Timing                    NaN     NaN    NaN  
Pulsation Timing Variations      NaN     NaN    NaN  
Radial Velocity                1.260  3.0000  25.00  
Transit                        1.470  1.4700   1.47  
Transit Timing Variations        NaN     NaN    NaN

#### Filter ####

In [107]:
df

method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1035 rows x 6 columns]

In [121]:
def filter_func(x):
    return x['year'].min()>9

In [122]:
df.groupby('method').filter(filter_func)

method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1035 rows x 6 columns]

In [149]:
def filter_func1(x):
    return x['mass'].mean()>3.5

In [152]:
df.groupby('method').filter(filter_func1)

method  number  orbital_period  mass  distance  year
32  Eclipse Timing Variations       1        10220.00  6.05       NaN  2009
37  Eclipse Timing Variations       2         5767.00   NaN    130.72  2008
38  Eclipse Timing Variations       2         3321.00   NaN    130.72  2008
39  Eclipse Timing Variations       2         5573.55   NaN    500.00  2010
40  Eclipse Timing Variations       2         2883.50   NaN    500.00  2010
41  Eclipse Timing Variations       1         2900.00   NaN       NaN  2011
42  Eclipse Timing Variations       1         4343.50  4.20       NaN  2012
43  Eclipse Timing Variations       2         5840.00   NaN       NaN  2011
44  Eclipse Timing Variations       2         1916.25   NaN       NaN  2011

#### Transform ####

#### 'Transform' runs as vectorel.We are able to run function on our variable that I want.Transform do not run as object variable in DataFrame because of useing 'iloc'. ####

In [189]:
df4=pd.DataFrame({'student_class':['A','B','C','A','B','C'],'lecture_degree':[12,11,98,55,45,70],'student_age':[12,45,25,32,20,63]},columns=['student_class','lecture_degree','student_age'])

In [190]:
df4

student_class  lecture_degree  student_age
0             A              12           12
1             B              11           45
2             C              98           25
3             A              55           32
4             B              45           20
5             C              70           63

In [191]:
df4['lecture_degree']*9

0    108
1     99
2    882
3    495
4    405
5    630
Name: lecture_degree, dtype: int64

In [192]:
df5=df4.iloc[:,1:2]
df5

lecture_degree
0              12
1              11
2              98
3              55
4              45
5              70

In [193]:
df5.transform(lambda x:(x.std()) / x*5)

lecture_degree
0       14.075072
1       15.354623
2        1.723478
3        3.070925
4        3.753352
5        2.412869

In [194]:
df5.transform(lambda x:(x-x.mean()) / x.std())

lecture_degree
0       -1.080516
1       -1.110119
2        1.465357
3        0.192421
4       -0.103611
5        0.636468

#### Apply ####

In [195]:
import numpy as np
import pandas as pd

In [196]:
df6=pd.DataFrame({'lecture_degree':[12,11,98,55,45,70],'student_age':[12,45,25,32,20,63]})
df6

lecture_degree  student_age
0              12           12
1              11           45
2              98           25
3              55           32
4              45           20
5              70           63

In [197]:
df6.apply(np.mean)

lecture_degree    48.500000
student_age       32.833333
dtype: float64

In [198]:
df6.apply(np.std)

lecture_degree    30.836937
student_age       16.925490
dtype: float64

In [203]:
df4

student_class  lecture_degree  student_age
0             A              12           12
1             B              11           45
2             C              98           25
3             A              55           32
4             B              45           20
5             C              70           63

In [205]:
df4.groupby('student_class').apply(np.sum)

student_class  lecture_degree  student_age
student_class                                           
A                        AA              67           44
B                        BB              56           65
C                        CC             168           88