### PANDAS ###

In [5]:
import pandas as pd

In [6]:
pd.Series([45,5455,55,12,225])

0      45
1    5455
2      55
3      12
4     225
dtype: int64

In [7]:
x=pd.Series([45,5455,55,12,225])

In [8]:
type(x)

pandas.core.series.Series

In [9]:
x.axes

[RangeIndex(start=0, stop=5, step=1)]

In [10]:
x.dtype

dtype('int64')

In [11]:
x.size

5

In [12]:
x.ndim

1

In [13]:
x.values

array([  45, 5455,   55,   12,  225], dtype=int64)

In [14]:
x.head(2)

0      45
1    5455
dtype: int64

In [15]:
x.tail(2)

3     12
4    225
dtype: int64

In [16]:
x=pd.Series([45,5455,55,12,225], index=[2,5,7,8,5])
x

2      45
5    5455
7      55
8      12
5     225
dtype: int64

In [17]:
x[1:3]

5    5455
7      55
dtype: int64

In [18]:
x[2]

45

In [19]:
x=pd.Series([45,5455,55,12,225], index=['x','y','z','t','m'])
x

x      45
y    5455
z      55
t      12
m     225
dtype: int64

In [20]:
x['y':'t']

y    5455
z      55
t      12
dtype: int64

In [21]:
x['z']

55

In [22]:
dicti={'std':15,'mean':45,'mod':5}

In [23]:
a=pd.Series(dicti)
a

std     15
mean    45
mod      5
dtype: int64

In [24]:
a[0]

15

In [25]:
a['std':'mean']

std     15
mean    45
dtype: int64

In [26]:
y=pd.Series([5,5,12,35])
y

0     5
1     5
2    12
3    35
dtype: int64

In [27]:
pd.concat([x,y])

x      45
y    5455
z      55
t      12
m     225
0       5
1       5
2      12
3      35
dtype: int64

In [28]:
pd.concat([x,a])

x         45
y       5455
z         55
t         12
m        225
std       15
mean      45
mod        5
dtype: int64

### Element operations ###

In [29]:
import numpy as np
import pandas as pd

In [30]:
t=np.array([4,5,6,8,9,12])

In [31]:
u=pd.Series(t)
u

0     4
1     5
2     6
3     8
4     9
5    12
dtype: int32

In [32]:
t[2]

6

In [33]:
t[1:4]

array([5, 6, 8])

In [34]:
u.index

RangeIndex(start=0, stop=6, step=1)

In [35]:
u.keys

<bound method Series.keys of 0     4
1     5
2     6
3     8
4     9
5    12
dtype: int32>

In [36]:
list(u.items())

[(0, 4), (1, 5), (2, 6), (3, 8), (4, 9), (5, 12)]

In [37]:
u.values

array([ 4,  5,  6,  8,  9, 12])

In [38]:
6 in u

False

In [39]:
1 in u

True

#### Fancy Element ####

In [40]:
u[[1, 2]]                       # give the name of series to find the value.

1    5
2    6
dtype: int32

In [41]:
u[1]

5

In [42]:
u[1]=555

In [43]:
u

0      4
1    555
2      6
3      8
4      9
5     12
dtype: int32

### Create a Dataframe ###

In [ ]:
p=[1,2,3,4,5,6,7]

In [ ]:
import pandas as pd

In [ ]:
pd.DataFrame(p, columns=['data'])

In [ ]:
import numpy as np

In [ ]:
s=np.arange(1,10).reshape(3,3)
s

In [ ]:
pd.DataFrame(s, columns=['data1','data2','data3'])             #create a dataframe from any numpy array.

In [ ]:
df=pd.DataFrame(s, columns=['value1','value2','value3'])
df

In [ ]:
df.columns

In [ ]:
df.columns=('x','y','z')
df

In [ ]:
type(df)

In [ ]:
df.axes

In [ ]:
df.shape

In [ ]:
df.ndim

In [ ]:
df.size

In [ ]:
df.values

In [ ]:
type(df.values)

In [ ]:
df.head()

In [ ]:
df.head(1)

In [ ]:
df.tail()

In [ ]:
df.tail(1)

#### Element Operations in DataFrame ####

In [ ]:
import numpy as np

In [ ]:
n1=np.random.randint(10, size=5)
n2=n1=np.random.randint(10, size=5)
n3=n1=np.random.randint(10, size=5)

In [ ]:
dicti={'m1':n1, 'm2':n2, 'm3':n3}

In [ ]:
dicti                                     # Values are numpy array.

In [ ]:
df=pd.DataFrame(dicti)
df                                        # The dataframe is from the dictionary. 

In [ ]:
df[0:1]

In [ ]:
df.index

In [ ]:
df.index=['a','b','c','d','e']
df

In [ ]:
df[:'a']

In [ ]:
df['a':'b']

In [ ]:
df['b':'d']

In [ ]:
g=['a']

In [ ]:
df.loc['b', 'm2']            #We want to see one element-loc

In [ ]:
df.loc['c', 'm2']

In [ ]:
df.(, axis=0)

#### Drop ####

In [ ]:
df.drop('a', axis=0)

In [ ]:
df.drop('m1', axis=1)

In [ ]:
df

In [ ]:
df.drop('b', axis=0, inplace=True)
df

In [ ]:
df.drop('m3', axis=1, inplace=True)
df

#### Fancy Operation ####

#### type : 1 ####

In [ ]:
y=['c','e']

In [ ]:
df.drop(y, axis=0)

In [ ]:
df

#### type : 2 ####

In [ ]:
df.drop(['c','e'], axis=0)

In [ ]:
df

In [ ]:
'm1' in df

In [ ]:
l=['var1','var2','m1','d']

In [ ]:
for i in l:
    print(i in df)

In [ ]:
df

In [ ]:
df['var4']=df['m1']*df['m2']

In [ ]:
df

In [ ]:
df.drop('var4', axis=1)

In [ ]:
df

df.drop('var4', axis=1, inplace=True)

In [ ]:
df.drop('m1', axis=1, inplace=True)

In [ ]:
df

In [ ]:
df.drop('c', axis=0, inplace=True)

In [ ]:
df

gözlem and değişken selection

In [ ]:
import numpy as np

In [ ]:
e=np.random.randint(1,30, size=(10,3))
e

In [ ]:
import pandas as pd

In [ ]:
df=pd.DataFrame(e, columns=['mean1','mean2','mean3'])
df

In [ ]:
df[0:3]

In [ ]:
df.loc[0:3]

In [ ]:
df.loc[4:6]                              #-6 include

In [ ]:
df.loc[:6]

In [ ]:
df.loc[4,'mean1']                        

In [ ]:
df.iloc[4:6]                           # up to 6

In [ ]:
df.iloc[:4,:1]   

In [ ]:
df.loc[:4,'mean2']

In [ ]:
df.iloc[:4]['mean2']

### Conditional ###

In [ ]:
import numpy as np

In [ ]:
p=np.random.randint(45, size=[9,5])
p

In [ ]:
import pandas as np

In [ ]:
q=pd.DataFrame(p)
q

In [ ]:
q=pd.DataFrame(p, columns=(['std1','std2','std3','std4','std5']))
q

In [ ]:
q['label']=q['std1']*q['std2']

In [ ]:
q

In [ ]:
q['label']

In [ ]:
q[:2][['std1','label']]        #If we see one more variable,we must use 'fancy'for instance:'std1' and 'label' is made a list.
                               #But when we see one or one more feature,we use ['any feature']or ['any feature':'any feature']

In [ ]:
q

In [ ]:
q[q.std1>12]                  #Select bigger than 12 number in 'std1'.

In [ ]:
q[q.std1>12]['std2']          #And than select this conclusion in 'std2'

In [ ]:
q[(q.std1>12) & (q.std4>15)]

example-1

In [ ]:
q.loc[(q.std1>12), ['std1', 'std2']]         

example-2

In [ ]:
q[(q.std1>12)][['std1','std2']]       #This is the same with 'example1'.

### Join ###

In [ ]:
import numpy as np

In [ ]:
w=np.array([452,5525,581848,1,233])                 #We use 'array' for one dimension.
w

In [ ]:
q=np.arange(0,30).reshape(5,6)                     #We use 'arange' for more one than dimension.
q

In [ ]:
pd.DataFrame(q)

In [ ]:
h=pd.DataFrame(q, columns=['colour_degree1','colour_degree2','colour_degree3','colour_degree4','colour_degree5','colour_degree6'])
h

In [ ]:
h2=h+5
h2

In [ ]:
pd.concat([h,h2])

In [ ]:
pd.concat([h,h2], ignore_index=True)

In [ ]:
h2

In [ ]:
h2.columns=['colour_degree1','colour_degree2','colour_degree3','colour_degree4','colour_high1','colour_high2']

In [ ]:
h2

In [ ]:
pd.concat([h,h2])

In [ ]:
pd.concat([h,h2], join='inner')

In [ ]:
pd.concat([h,h2] join_axes =[h2.columns])

### Advanced Join ###

In [ ]:
import pandas as pd

In [ ]:
df1=pd.DataFrame({'staff_name':['john','george','maria','ali'],
                 'staff_age':[5,5,64,18]})
df1

In [ ]:
df2=pd.DataFrame({'staff_name':['john','george','maria','ali'],'start_work':[2000,2001,2002,2003]})
df2

In [ ]:
df3=pd.merge(df1,df2)  
df3                                              #'merge' is a  one-to-one merge

In [ ]:
pd.merge(df1,df2, on ='staff_name')

In [ ]:
df4=pd.DataFrame({'staff_age':[5,5,64], 'staff_periyod':['morning','noon','evening']})
df4                                                                                      #many-to-one merge

In [ ]:
pd.merge(df3,df4)

In [ ]:
df5=({'staff_name':['john','george','maria','ali',''],})                                                                                               #many to many

### Agreegation and Grouping ###

Agreegation Functions
* count() - 
* first()-
* last()-
* mean()-
* median()-
* min()-
* max()-
* std()-
* var()-
* sum()-

In [ ]:
import seaborn as sns

In [ ]:
df=sns.load_dataset('planets')
df

In [ ]:
df.head(15)

In [ ]:
df.shape

In [ ]:
df.count()

In [ ]:
df['number'].count()

In [ ]:
df.first()

In [ ]:
df.last()

In [ ]:
df.mean()

In [ ]:
df['mass'].mean()

In [ ]:
df.median()

In [ ]:
df['distance'].median()

In [ ]:
df.std()

In [ ]:
df['orbital_period'].std()

In [ ]:
df.var()

In [ ]:
df['year'].var()

In [ ]:
df.sum()

In [ ]:
df['mass'].sum()

In [ ]:
df.max()

In [ ]:
df['mass'].max()

In [ ]:
df.min()

In [ ]:
df['distance'].min()

In [ ]:
df.describe()

In [ ]:
df.describe().T

In [ ]:
df.dropna().describe()                            #We see missing valuble with 'dropna'

#### Aggregate ####

#### We only see statistics values with 'aggregate' that we want. ####

In [ ]:
df3=pd.DataFrame({'student_class':['A','B','C','A','B'],'student_degree':[25,45,23,85,98],'student_age':[12,13,11,10,14]})
df3

In [ ]:
df3.groupby('student_class')

In [ ]:
df3.groupby('student_class').mean()

In [ ]:
df3.groupby('student_class').aggregate([max, min])

In [ ]:
df

In [ ]:
df.head(5)

In [ ]:
df.groupby('method').aggregate([min, max])

In [ ]:
df.groupby('method')['mass'].aggregate([min, max])

#### Grouping ####

#### We are able to use 'groupby',if data type is categoric. ####

In [ ]:
df1=pd.DataFrame({'student_class':['A','B','A','B'],'lecture_degree':[45,52,17,99]})

In [ ]:
df1

In [ ]:
df1.groupby('student_class')

In [ ]:
df1.groupby('student_class').mean()

In [ ]:
df1.groupby('student_class').sum()

In [ ]:
df

In [ ]:
df.groupby('method').std()

In [ ]:
df.groupby('method').std().head(3)

In [ ]:
df.groupby('method')['mass']

In [ ]:
df.groupby('method')['mass'].mean()

In [ ]:
df.groupby('method')['mass'].describe()

#### Filter ####

In [ ]:
df

In [ ]:
def filter_func(x):
    return x['year'].min()>9

In [ ]:
df.groupby('method').filter(filter_func)

In [ ]:
def filter_func1(x):
    return x['mass'].mean()>3.5

In [ ]:
df.groupby('method').filter(filter_func1)

#### Transform ####

#### 'Transform' runs as vectorel.We are able to run function on our variable that I want.Transform do not run as object variable in DataFrame because of useing 'iloc'. ####

In [ ]:
df4=pd.DataFrame({'student_class':['A','B','C','A','B','C'],'lecture_degree':[12,11,98,55,45,70],'student_age':[12,45,25,32,20,63]},columns=['student_class','lecture_degree','student_age'])

In [ ]:
df4

In [ ]:
df4['lecture_degree']*9

In [ ]:
df5=df4.iloc[:,1:2]
df5

In [ ]:
df5.transform(lambda x:(x.std()) / x*5)

In [ ]:
df5.transform(lambda x:(x-x.mean()) / x.std())

#### Apply ####

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df6=pd.DataFrame({'lecture_degree':[12,11,98,55,45,70],'student_age':[12,45,25,32,20,63]})
df6

In [ ]:
df6.apply(np.mean)

In [ ]:
df6.apply(np.std)

In [ ]:
df4

In [ ]:
df4.groupby('student_class').apply(np.sum)